const projectsList = [
  {
    id: 1,
    name: "Portfolio photographe",
    link: "https://sbirlobo.github.io/portfolio_project1/",
    code: "https://github.com/SbirLobo/portfolio_project1",
    image: "/p1.png",
    startDate: "2023/03/08",
    endDate: "2023/03/24",
    duration: "5 jours",
  },
  {
    id: 2,
    name: "Blurtest",
    link: "blurtest.remote-fr-2.wilders.dev/",
    code: "https://github.com/SbirLobo/Blutest",
    image: "/p2.png",
    startDate: "2023/04/05",
    endDate: "2023/05/05",
    duration: "10 jours",
  },
  {
    id: 3,
    name: "Choixteau",
    link: "https://choixteau.netlify.app/",
    code: "https://github.com/SbirLobo/Choixteau",
    image: "/p3.png",
    startDate: "2023/04/11",
    endDate: "2023/04/12",
    duration: "36 heures...",
  },
  {
    id: 4,
    name: "ACS Psychologue",
    link: "http://acs-psychologue.fr/",
    code: "https://github.com/SbirLobo/acs-psychologue",
    image: "/acs.png",
    startDate: "2023/04/11",
    endDate: "2023/04/12",
    duration: "3 jours",
  },
  {
    id: 5,
    name: "Portfolio DevWeb",
    link: "",
    code: "https://github.com/SbirLobo/Portfolio_DevWeb",
    image: "/portfolio.png",
    startDate: "2023/05/28",
    endDate: "2023/05/31",
    duration: "3 jours",
  },
];

export default projectsList;
